CREATE TABLE CUSTOMER (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	name		VARCHAR(32) NOT NULL,
	address		VARCHAR(255) NOT NULL,
	site_url	VARCHAR(64),
	PRIMARY KEY (id)
);

CREATE TABLE PROJECT (
	id	    	BIGINT NOT NULL AUTO_INCREMENT,
	name		VARCHAR(32) NOT NULL,
	description	VARCHAR(255) NOT NULL,
	customer_id	BIGINT,
	PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id)
);

CREATE TABLE EMPLOYEE (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	first_name	VARCHAR(32) NOT NULL,
	last_name	VARCHAR(32) NOT NULL,
	birth_date	DATE,
	photo_id	BIGINT,
	PRIMARY KEY (id)
);

CREATE TABLE EMPLOYEE_PHOTO (
	id	    	BIGINT NOT NULL,
	photo		BLOB,
	PRIMARY KEY (id)
);

CREATE TABLE PROJECT_EMPLOYEE (
	project_id  	BIGINT NOT NULL,
	employee_id 	BIGINT NOT NULL,
	PRIMARY KEY (project_id, employee_id)
);
